### ISSUE TITLE
Todo list: Half-baked bits

### ISSUE THREAD

**Issue by Fuzzyzilla** [Fuzzyzilla/fuzzpaint#34]
There's a couple of things that are 50-90% implemented that i stopped and merged because i got worn out/burnt out that I really must revisit and spring-clean. Todo list :3

* [ ] Partial state clones - left as a `todo!()` but never used. Could present a substantial performance boost on large documents (which given the state of things is not likely to be a problem in the app's current form :P)
* [ ] File IO - left as a skeleton that saves and loads the bare minimum to prove to myself that it was "working"
* [ ] Object pickers - go real bogged down in API design and after completely stagnating I merged it to avoid divergent histories. Never called into.
* [ ] Text rendering - similar story as above.
